### ISSUE TITLE
Fix problems with production site

### ISSUE THREAD

**Issue by kz-userstat** [kazstat/sdg-site-kazstat#13]
Problems on production site:
* Base URL should be blank
* CSS files cannot be loaded

**Comment by brockfanning** [comment]
@kz-userstat Let's see if the production problems have been fixed. Can you perform a "production release"?

You can either do this on the command-line or in GitHub. Here are the commands to use the command line:
```
git checkout develop
git pull origin develop
git checkout master
git pull origin master
git merge develop
git push origin master
```

**Comment by brockfanning** [comment]
@kazstat/drasticals This is fixed now - here is the production site: https://sdg-kazstat.github.io/
(It will eventually have it's custom domain name.)

**Comment by brockfanning** [comment]
I will go ahead and close this issue, since it is fixed.
