### ISSUE TITLE
Goal layout with target rows and indicator grids below

### ISSUE THREAD

**Issue by brockfanning** [kazstat/sdg-site-kazstat#18]
An alternative goal layout, with rows for each target, and a grid of indicators beneath each target row.

**Comment by brockfanning** [comment]
@ainurchik @kz-userstat
Do you have any feedback about this mockup?

![screencapture-127-0-0-1-4000-sdg-site-kazstat-1-2019-05-28-17_19_35](https://user-images.githubusercontent.com/1319083/58513455-85ef9480-816d-11e9-8268-7510fbb8c08a.png)

**Comment by ainurchik** [comment]
Dear Brock,

generally is looks ok, but we discussed with colleagues and think about exclusion the category of indicators (глобальный с изменениями, альтернативный национальный, дополнительный национальный).. We can write about these categories in metadata....What do you think?

With warm regards,
Ainur
>Среда, 29 мая 2019, 3:25 +06:00 от brockfanning <notifications@github.com>:
>
>@ainurchik @kz-userstat
>Do you have any feedback about this mockup?
>
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Ainura Dossanova

**Comment by brockfanning** [comment]
@ainurchik Yes, I agree that makes it look much cleaner. Here is another screenshot for you to review:

![screencapture-127-0-0-1-8000-sdg-site-kazstat-1-2019-05-30-22_14_20](https://user-images.githubusercontent.com/1319083/58677053-7ff1e300-8328-11e9-8a23-91a73ae618b2.png)

**Comment by brockfanning** [comment]
@ainurchik @aigerim1103 I've put this layout up on [the site](https://kazstat.github.io/sdg-site-kazstat/) so that you can get a better look. Any feedback on the layout of the goal pages?

**Comment by ainurchik** [comment]
Dear Brock,

many thanks! What you think about version US:



May be we make same layout, but with target rows?
First - target row, then indicators...

best, Ainur


>Четверг, 13 июня 2019, 6:33 +06:00 от brockfanning <notifications@github.com>:
>
>@ainurchik @aigerim1103 I've put this layout up on  the site so that you can get a better look. Any feedback on the layout of the goal pages?
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Ainura Dossanova

**Comment by brockfanning** [comment]
@ainurchik I've made this change on [the site](https://kazstat.github.io/sdg-site-kazstat/). Any feedback?

**Comment by brockfanning** [comment]
I believe we have settled on a goal page layout, so I will close this issue.
