### ISSUE TITLE
Add space on the page for infographics 

### ISSUE THREAD

**Issue by kz-userstat** [kazstat/sdg-site-kazstat#21]

**Comment by kz-userstat** [comment]
It is long term issue that doesn't require solution

**Comment by brockfanning** [comment]
@ainurchik Here is an example of an infographic at the target level. See [target 1.a here](https://kazstat.github.io/sdg-site-kazstat/1/).

@Zhanybek Here is an example of the [data file](https://github.com/kazstat/sdg-site-kazstat/blob/develop/data/translations/kz/infographics.yml) that controls this. It is only using a placeholder image now.

**Comment by ainurchik** [comment]
Dear Brock,

many thanks! it looks well, I think when we insert infographic it will great...But I have question: we will have same place after each target?

With warm regards,
Ainur


>Среда, 19 июня 2019, 6:50 +06:00 от brockfanning <notifications@github.com>:
>
>@ainurchik Here is an example of an infographic at the target level. See  target 1.a here .
>@Zhanybek Here is an example of the  data file that controls this. It is only using a placeholder image now.
>—
>You are receiving this because you were mentioned.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

-- 
Ainura Dossanova

**Comment by brockfanning** [comment]
@ainurchik As an example I've put infographics on all of the targets for Goal 1, [see here](https://kazstat.github.io/sdg-site-kazstat/1/). What do you think of this approach?

**Comment by brockfanning** [comment]
Since we are getting close to launch, I removed the placeholder images. But I believe this task is complete.

**Comment by ainurchik** [comment]
Yes, of cource.  Brock
