### ISSUE TITLE
Import data

### ISSUE THREAD

**Issue by kz-userstat** [kazstat/sdg-site-kazstat#6]

**Comment by brockfanning** [comment]
Some feedback and tasks on this:

4-2-1
    - Urban is missing
    - Adjust disaggregation table
        - Make cities uniquely labeled
    - import spreadsheet lines 209 and 217 should not be connected
        - better recognize combined disaggregations

4-c-1
    - Line 986 - space is missing

Create report of all skipped disaggregations

**Comment by brockfanning** [comment]
Another data import has been submitted as a pull-request: https://github.com/kazstat/sdg-data-kazstat/pull/7

**Comment by brockfanning** [comment]
@kz-userstat @ainurchik This latest import is ready for review. For example, how does 4.2.1 look? https://kazstat.github.io/sdg-site-kazstat/4-2-1/

**Comment by brockfanning** [comment]
@ainurchik @aigerim1103 The latest (4th) data import is up on [the site](https://kazstat.github.io/sdg-site-kazstat/) and ready for review. As you browse the indicators, do you see any problems in the disaggregations and/or the graphs?

**Comment by brockfanning** [comment]
One issue I notice: 1-5-2 has some missing disaggregation. It needs to be re-imported after these have been added to the disaggregation file, with an appropriate category:
* Сумма ущерба от чрезвычайных ситуаций природного  характера
* Сумма ущерба от чрезвычайных ситуаций техногенного характера

**Comment by brockfanning** [comment]
The 4-digit problem should be fixed now. I'm continuing to look for disaggregation problems.

**Comment by brockfanning** [comment]
Remaining tasks:
* 4-3-1: This should be changed into 3 separate national indicators, including the 2 rows beneath it

**Comment by brockfanning** [comment]
Since the data import has been completed, I will go ahead and close this issue.
